backend:
  name: git-gateway

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  #- name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
  #  label: "Post" # Used in the UI, ie.: "New Post"
  #  folder: "content/blog" # The path to the folder where the documents are stored
  #  create: true # Allow users to create new documents in this collection
  #  fields: # The fields each document in this collection have
  #    - {label: "Title", name: "title", widget: "string"}
  #    - {label: "Publish Date", name: "date", widget: "datetime"}
  #    - {label: "Image", name: "banner", widget: "image", required: false}
  #    - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "Home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Banner Background Image, name: jumbotron_bg_img, widget: image}
          - {label: Banner Logo, name: jumbotron_logo_img, widget: image}
          - {label: Show Alert, name: alert, widget: boolean, default: false}
          - {label: Alert Announcment, name: alert_announcement, widget:string}
          - {label: Welcome Message Heading, name: welcome_message_heading, widget: string}
          - {label: Welcome Message, name: welcome_message, widget: text}
          - {label: Welcome Message Button Text, name: welcome_message_button_text, widget: string}
          - {label: Welcome Message Button Link, name: welcome_message_button_URL, widget: string}
          - label: "Front Boxes"
            name: "front_boxes"
            widget: list
            fields:
              - {label: Headings, name: heading, widget: string}
              - {label: Link, name: url, widget: string}
              - {label: Icon, name: icon, widget: string}
          - {label: Front Section 2 Heading, name: front_more_heading, widget: string}
          - {label: Front Section 2 Text, name: front_more_text, widget: string}
          - {label: Front Section 2 Button Text, name: front_more_button_text, widget: string}
          - {label: Front Section 2 Button Link, name: front_more_button_url, widget: string}
          - {label: Front Last Background Image, name: front_last_bg_img, widget: image}
          - {label: Front Last Heading, name: front_last_heading, widget: string}
          - {label: Front Last Text Lead, name: front_last_text_lead, widget: string}
          - {label: Front Last Text, name: front_last_text, widget: string}
          - {label: Front Last Button Text, name: front_last_button_text, widget: string}
          - {label: Front Last Button Link, name: front_last_button_url, widget: string}
      - file: "content/contact.md"
        label: "Contact Us"
        name: "contact"
        fields:
          - {label: Contact Us, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Top Content Heading, name: top_content_heading, widget: string}
          - {label: Top Content, name: top_content, widget: string}
          - {label: Staff Heading, name: staff_heading, widget: string}
          - {label: Staff Text, name: staff_subtext, widget: text}
          - label: "Staff"
            name: "staff"
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Contact Info, name: contact, widget: string}
              - {label: Image, name: img, widget: image}


  - name: "masses"
    label: "Masses"
    files:
      - file: "data/mass_times.yaml"
        label: "Mass Times"
        name: "mass_times"
        create: true
        fields:
          - label: "Mass Times"
            name: "mass_times"
            create: true
            widget: list
            fields:
              - {label: Day, name: day, widget: string}
              - {label: Time, name: time, widget: string}
  - name: "data"
    label: "Settings"
    files:
      - file: "data/settings.yaml"
        label: "Site Settings"
        name: "site_settings"
        fields:
          - {label: Site Title, name: site_title, widget: string}
          - {label: Site Address, name: site_address, widget: string}
          - {label: Site City, name: site_city, widget: string}
          - {label: Site State, name: site_state, widget: string}
          - {label: Site Zip, name: site_zip, widget: string}
          - {label: Phone Number (XXX) XXX-XXXX, name: site_phone, widget: string}
          - {label: Fax Number (XXX) XXX-XXXX, name: site_fax, widget: string}
          - {label: Email, name: site_email, widget: string}
          - {label: ChurchDB URL, name: site_churchDBURL, widget: string}
          - {label: eGiving URL, name: site_eGiving, widget: string}
          - {label: Site Footer Image, name: site_footer_img, widget: image}
